### ISSUE TITLE
Errors in the log file (whilst someone was trying to bot)

### ISSUE THREAD

**Issue by SimonOrJ** [Barbosik/MultiOgar#186]
```
[FATAL] Error: continuation frame cannot follow current opcode
    at Receiver.error (/home/simonorj/server/instantmultiogar/node_modules/ws/lib/Receiver.js:321:18)
    at Receiver.processPacket (/home/simonorj/server/instantmultiogar/node_modules/ws/lib/Receiver.js:220:12)
    at Receiver.add (/home/simonorj/server/instantmultiogar/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/home/simonorj/server/instantmultiogar/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
```

Also, there was this error on the logs for some IPs at random as well:
```
[ERROR][00:54:53] [<Botter's IP>:59265] Error: reserved fields must be empty
    at Receiver.error (/home/simonorj/server/instantmultiogar/node_modules/ws/lib/Receiver.js:321:18)
    at Receiver.processPacket (/home/simonorj/server/instantmultiogar/node_modules/ws/lib/Receiver.js:203:12)
    at Receiver.add (/home/simonorj/server/instantmultiogar/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/home/simonorj/server/instantmultiogar/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
```

**Comment by Barbosik** [comment]
if it doesn't crash the server it's ok. This log record just indicate that client doesn't close connection properly.
The connection with this IP:PORT should be closed, you can check it with 'sudo netstat -ntop'.
If connection still in the list with disabled timer (value in the timer column is 'off') it will leads to memory leaks. Let me know if you catch such condition.

**Comment by SimonOrJ** [comment]
Latest

**Comment by SimonOrJ** [comment]
I set the board to "Restarting...", and the game decided that it's the best time to crash after around 30 seconds after the board change. This error was followed by a botter's attempt to spawn in minions.

**Comment by Barbosik** [comment]
I'm asking because server crash was fixed in 1.2.35. So, if you get fatal error on version 1.2.35 or higher. 
It's a bug. For version <= 1.2.34 server crash on such error is normal, because fix is missing in old versions.

**Comment by Barbosik** [comment]
regarding to errors. I think it hapens because unexpected break of connection. cellcraft client using invlid protocol (hand made modified), and cannot works with non craftcell servers. So, it's crashed after connection and connection is terminated. I think some botter trying to use craftcell extension to connect to normal private servers. It's good because his minion extension will works on craftcell servers only

**Comment by Barbosik** [comment]
There is need for login system to provide reliable minion ban functionality.
Currently I'm working on the client which will support login. 
I think I will use google or fb authentication, the same as vanilla client.

**Comment by SimonOrJ** [comment]
Running version was 1.2.38.

I hope there's a way to stop bad clients from spamming the log with non-empty field error. It's making the logs harder to read...

**Comment by Barbosik** [comment]
SimonOrJ: swallow errors is a bad practice. Because one of these errors records can help to understand what happens if server will be crashed later. So, it should be present in the log, even if it's normal behavior.

Previous server log is copied into LogBackup folder, with adding backup timestamp to it's name.
So, you can just delete outdated logs in LogBackup folder by it's date.

**Comment by Barbosik** [comment]
fixed. Now a lot of errors just doesn't happens :)

**Comment by SimonOrJ** [comment]
That's great, thanks! :D

I did self-write a small shell command to allow me to filter through the logs meanwhile, haha :)

filter.sh:
```sh
#!/bin/sh
rm out.log
if [ -z ${3} ]
then
    if [ -z ${2} ]
    then
        echo "check out.log"
        grep '^\[' ${1} >> out.log
    else
        echo "variable 2 detected: $2"
        grep "$2" ${1} >> out.log
    fi
else
    grep "$2" ${1}
fi
```
