### ISSUE TITLE
Sorry i just need help.

### ISSUE THREAD

**Issue by ElMay0r** [Barbosik/MultiOgar#212]
Hello, 

I been using cigar since last year (I update all releases)

My server www.Agar.Blue has been targeted on a Bots (Minions) spammer, and every time they spam the Bot make my server Crash!

Here's the error that shows the console: 

> Error: Uncaught, unspecified "error" event. (reserved fields must be empty)
    at WebSocket.emit (events.js:144:17)
    at Receiver.onerror (C:\Users\Administrador\Desktop\Cigar-master\server\node
_modules\ws\lib\WebSocket.js:832:10)
    at Receiver.error (C:\Users\Administrador\Desktop\Cigar-master\server\node_m
odules\ws\lib\Receiver.js:317:8)
    at Receiver.processPacket (C:\Users\Administrador\Desktop\Cigar-master\serve
r\node_modules\ws\lib\Receiver.js:191:12)
    at Receiver.add (C:\Users\Administrador\Desktop\Cigar-master\server\node_mod
ules\ws\lib\Receiver.js:91:24)
    at Socket.firstHandler (C:\Users\Administrador\Desktop\Cigar-master\server\n
ode_modules\ws\lib\WebSocket.js:774:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)

Any solution? :'( (Sorry i know this is not Cigar, but i think this could be global.)

**Comment by Barbosik** [comment]
All these issues were fixed in MultiOgar

**Comment by ElMay0r** [comment]
Yes, but Multiogar doesnt let me host multiple game servers like CigarMaster :-1:

**Comment by NatsuTheGreat** [comment]
Then use Cigar.

**Comment by Barbosik** [comment]
If you want to host multiple game servers like CigarMaster, then use CigarMaster
