### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by PrinceDark9243** [Barbosik/MultiOgar#288]
I got this Error when i eject mass in latest 1.2.69

D:\Users\Papa\Desktop\Ogar Server 1.2.69\src>node index.js
[INFO ] MultiOgar 1.2.69 - An open source multi-protocol ogar server
[INFO ] 0 IP ban records loaded.
[WARN ] User account "Local Administrator" disabled
[WARN ] User account "Local Moderator" disabled
[WARN ] User account "Local User" disabled
[INFO ] 0 user records loaded.
[INFO ] 25 bad words loaded
[WARN ] TLS: not supported (SSL certificate not found!)
[INFO ] WebSocket: ws
[INFO ] Started stats server on port 88
[INFO ] Listening on port 28
[INFO ] Current game mode is Free For All
>[FATAL] TypeError: Cell.setSize: size is NaN
    at Cell.setSize (D:\Users\Papa\Desktop\Ogar Server 1.2.69\src\entity\Cell.js
:56:15)
    at GameServer.ejectMass (D:\Users\Papa\Desktop\Ogar Server 1.2.69\src\GameSe
rver.js:1342:14)
    at PlayerTracker.pressW (D:\Users\Papa\Desktop\Ogar Server 1.2.69\src\Player
Tracker.js:489:25)
    at PacketHandler.process (D:\Users\Papa\Desktop\Ogar Server 1.2.69\src\Packe
tHandler.js:219:35)
    at PlayerTracker.updateTick (D:\Users\Papa\Desktop\Ogar Server 1.2.69\src\Pl
ayerTracker.js:284:31)
    at GameServer.updateClients (D:\Users\Papa\Desktop\Ogar Server 1.2.69\src\Ga
meServer.js:542:39)
    at GameServer.mainLoop (D:\Users\Papa\Desktop\Ogar Server 1.2.69\src\GameSer
ver.js:679:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

D:\Users\Papa\Desktop\Ogar Server 1.2.69\src>pause
Press any key to continue . . .

**Comment by PrinceDark9243** [comment]
sorry my bad i isnt set the ejectmass loss amount sorry :)
