### ISSUE TITLE
MultiOgar Problem in VPS

### ISSUE THREAD

**Issue by malekksa505** [Barbosik/MultiOgar#473]
Hello ..

When playing in the game .. shows me a message in the vps containing

`[FATAL] TypeError: Cannot read property 'destroy' of null
    at GameServer.onClientSocketClose (/root/MultiOgar1/src/GameServer.js:315:19                           )
    at WebSocket.onClose (/root/MultiOgar1/src/GameServer.js:287:14)
    at emitTwo (events.js:105:20)
    at WebSocket.emit (events.js:185:7)
    at WebSocket.emitClose (/root/MultiOgar1/node_modules/ws/lib/WebSocket.js:22                           6:10)
    at /root/MultiOgar1/node_modules/ws/lib/WebSocket.js:212:41
    at Receiver.cleanup (/root/MultiOgar1/node_modules/ws/lib/Receiver.js:518:15                           )
    at WebSocket.finalize (/root/MultiOgar1/node_modules/ws/lib/WebSocket.js:212                           :22)
    at emitNone (events.js:85:20)
    at Socket.emit (events.js:179:7)

And then the game stops , What is the solution my friends`

**Comment by ItzLevvie** [comment]
@malekksa505 https://github.com/Megabyte918/MultiOgar-Edited/issues/492#issuecomment-277460015

**Comment by malekksa505** [comment]
Thx

**Comment by Logan7432** [comment]
What vps do you use?
