### ISSUE TITLE
My server won't let I join when I attempt to join.

### ISSUE THREAD

**Issue by kevdaawsome** [Barbosik/MultiOgar#488]
=== Started 2017-09-14T16-32-28-774 ===
[INFO ][16:32:28] [1m[32mMultiOgar 1.2.69[37m - An open source multi-protocol ogar server[0m
[INFO ][16:32:28] 0 IP ban records loaded.
[WARN ][16:32:28] User account "Local Administrator" disabled
[WARN ][16:32:28] User account "Local Moderator" disabled
[WARN ][16:32:28] User account "Local User" disabled
[INFO ][16:32:28] 0 user records loaded.
[INFO ][16:32:28] 25 bad words loaded
[WARN ][16:32:28] TLS: not supported (SSL certificate not found!)
[INFO ][16:32:28] WebSocket: ws
[INFO ][16:32:28] Started stats server on port 88
[INFO ][16:32:29] Listening on port 1213
[INFO ][16:32:29] Current game mode is Free For All
                                                      **This is when I join**
[FATAL][16:39:27] TypeError: Cannot read property 'headers' of undefined
    at GameServer.onClientSocketOpen (C:\Users\Kev 123 the boss\Desktop\Other\Agar.io Private Server\MultiOgar-master\src\GameServer.js:273:107)
    at emitTwo (events.js:125:13)
    at WebSocketServer.emit (events.js:213:7)
    at handleUpgrade (C:\Users\Kev 123 the boss\Desktop\Other\Agar.io Private Server\MultiOgar-master\node_modules\ws\lib\WebSocketServer.js:88:16)
    at WebSocketServer.completeUpgrade (C:\Users\Kev 123 the boss\Desktop\Other\Agar.io Private Server\MultiOgar-master\node_modules\ws\lib\WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (C:\Users\Kev 123 the boss\Desktop\Other\Agar.io Private Server\MultiOgar-master\node_modules\ws\lib\WebSocketServer.js:197:10)
    at Server.WebSocketServer._ultron.on (C:\Users\Kev 123 the boss\Desktop\Other\Agar.io Private Server\MultiOgar-master\node_modules\ws\lib\WebSocketServer.js:87:14)
    at emitThree (events.js:135:13)
    at Server.emit (events.js:216:7)
    at onParserExecuteCommon (_http_server.js:493:14)
[DEBUG][16:39:27] process.exit(1)
=== Shutdown 2017-09-14T16-39-27-995 ===

**Comment by Agarian** [comment]
As much as I wish it weren't true, @Barbosik has abandoned the REPO, so a fix is unlikely.
However, you can try https://github.com/Megabyte918/MultiOgar-Edited
