### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Faris90** [Barbosik/MultiOgar#495]
How could I fix this:
[FATAL] TypeError: Cannot read property 'headers' of undefined
    at GameServer.onClientSocketOpen (/home/ubuntu/workspace/src/GameServer.js:273:107)
    at emitTwo (events.js:106:13)
    at WebSocketServer.emit (events.js:191:7)
    at handleUpgrade (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:88:16)
    at WebSocketServer.completeUpgrade (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:197:10)
    at Server.WebSocketServer._ultron.on (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:87:14)
    at emitThree (events.js:116:13)
    at Server.emit (events.js:194:7)
    at onParserExecuteCommon (_http_server.js:409:14)

**Comment by ItzLevvie** [comment]
@Faris90 see changes here https://github.com/Megabyte918/MultiOgar-Edited/pull/1305/files#diff-ee5616beb8aa0f352a3f697cf7c1d331

**Comment by agarian-2** [comment]
Refer to #499 @Faris90
