### ISSUE TITLE
Fatal Error: Unexpected token

### ISSUE THREAD

**Issue by UnRealm** [Barbosik/MultiOgar#505]
Hi, i try to run server on my server Ubuntu 18.4
I've executed only these commands:
`sudo apt-get update`
`sudo apt-get install git`
`sudo apt-get install nodejs-legacy npm`
`git clone git://github.com/Barbosik/MultiOgar.git`
`cd MultiOgar`
`npm install`
`cd src`
`sudo node index.js`

After the last command I receive error

> [FATAL] SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/var/www/multiogar/node_modules/ws/index.js:3:19)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)

How can I fix it?
![image](https://i.imgur.com/ljDRgv8.png)

**Comment by josefredohd** [comment]
try changing the ws version from latest to 1.0.0 of the package.json file

**Comment by josefredohd** [comment]
and use npm install again

**Comment by josefredohd** [comment]
https://hastebin.com/keluguqaxa.json

**Comment by josefredohd** [comment]
@UnRealm Has it worked for you?
