### ISSUE TITLE
Errorrr

### ISSUE THREAD

**Issue by pranshuthegamer** [Barbosik/MultiOgar#508]
[FATAL] TypeError: Cannot read property 'headers' of undefined
    at GameServer.onClientSocketOpen (/home/shivangi/pranshu/MultiOgar/src/GameServer.js:273:108)
    at WebSocketServer.emit (events.js:198:13)
    at handleUpgrade (/home/shivangi/pranshu/MultiOgar/node_modules/ws/lib/websocket-server.js:90:18)
    at WebSocketServer.completeUpgrade (/home/shivangi/pranshu/MultiOgar/node_modules/ws/lib/websocket-server.js:329:5)
    at WebSocketServer.handleUpgrade (/home/shivangi/pranshu/MultiOgar/node_modules/ws/lib/websocket-server.js:245:10)
    at Server.upgrade (/home/shivangi/pranshu/MultiOgar/node_modules/ws/lib/websocket-server.js:89:16)
    at Server.emit (events.js:198:13)
    at onParserExecuteCommon (_http_server.js:567:14)
    at socketOnData (_http_server.js:494:3)
    at Socket.emit (events.js:198:13)

**Comment by ItzLevvie** [comment]
@PranshuTG https://github.com/m-byte918/MultiOgarII/pull/1305/files#diff-ee5616beb8aa0f352a3f697cf7c1d331.
