### ISSUE TITLE
Error when I use commands 

### ISSUE THREAD

**Issue by David1ali12** [Barbosik/MultiOgar#87]
I updated my MultiOgar server but I get an error when I use commands help
    at next (native)

```
[Game] Ogar - An open source Agar.io server implementation
[INFO ] 0 IP ban records loaded.
[OgarConsole] >> Runnin on port >> 2000
[OgarConsole] >> Version: 1.0.2
[INFO ] Started stats server on port 8081
[INFO ] Listening on port 443
[INFO ] Current game mode is Free For All
>addbot 10
readline.js:925
            throw err;
            ^

TypeError: Cannot read property 'onCommand' of undefined
    at parseCommands (/root/agarlist/MultiOgar/src/index.js:50:19)
    at /root/agarlist/MultiOgar/src/index.js:43:9
    at Interface._onLine (readline.js:209:5)
    at Interface._line (readline.js:550:8)
    at Interface._ttyWrite (readline.js:827:14)
    at ReadStream.onkeypress (readline.js:106:10)
    at emitTwo (events.js:100:13)
    at ReadStream.emit (events.js:185:7)
    at emitKeys (readline.js:1251:14)
    at next (native)

```

**Comment by Barbosik** [comment]
it's your mod issue, there is no such error in MultiOgar

**Comment by Megabyte918** [comment]
I get indexOf is undefined when i use the "change" command on nothing :P

**Comment by Barbosik** [comment]
**Megabyte918**: what exactly command did you used and what exactly error it shows?

**Comment by Barbosik** [comment]
I fixed error logging, so now errors which previously was hidden is displayed in the log

**Comment by Barbosik** [comment]
hm, it's really throws error when change command executed with no argument, it's because it should be used with arguments :)

**Comment by Megabyte918** [comment]
I used `change playerStartMass 132` and i got this:
<pre>readline.js:925
            throw err;
            ^

TypeError: Cannot read property 'indexOf' of undefined
    at Commands.list.change (C:\Users\Christian\Desktop\MultiOgar-master\src\modules\CommandList.js:217:21)
    at parseCommands (C:\Users\Christian\Desktop\MultiOgar-master\src\index.js:69:9)
    at C:\Users\Christian\Desktop\MultiOgar-master\src\index.js:45:13
    at Interface._onLine (readline.js:209:5)
    at Interface._line (readline.js:550:8)
    at Interface._ttyWrite (readline.js:827:14)
    at ReadStream.onkeypress (readline.js:106:10)
    at emitTwo (events.js:100:13)
    at ReadStream.emit (events.js:185:7)
    at emitKeys (readline.js:1251:14)
</pre>
It crashes the server and the same thing happens when i just type "change" and nothing else

**Comment by Megabyte918** [comment]
Can you make it so it doesn't crash the server

**Comment by Barbosik** [comment]
it's correct behavior to stop the server if some unexpected error happens, because this error should be fixed

**Comment by Barbosik** [comment]
error handling for command change fixed

**Comment by David1ali12** [comment]
Thanks :)
